#!/bin/bash

mkdir -p ~/workspace_SPD_intention_comm
cd ~/workspace_SPD_intention_comm
mkdir -p ~/workspace_SPD_intention_comm/src
cd  ~/workspace_SPD_intention_comm/src
git clone https://git.ropod.org/eduardocd/ropod_teleop.git
git clone https://git.ropod.org/ropod/communication/ropod_ros_msgs.git
git clone -b Eduardo https://github.com/HBRS-SDP/sdp_ss2019_P6_IntentionComm.git


# ### Catkin build
# source ~/ropod-project-software/catkin_workspace/src/platform/ropod_tue_1_bringup/setup.bash
# rosdep update
# rosdep install --from-path . -i -y
# cd ~/workspace_SPD_intention_comm
# catkin build
